[package]
name = "mkrp-rpa"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
byteorder.workspace = true
flate2.workspace = true
serde.workspace = true
serde-pickle = "1.2"
tracing.workspace = true
log.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile = "3.17"
