[package]
name = "mkrp-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
log.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
fast_image_resize = "5.1"
libloading.workspace = true
fontdue.workspace = true
zenavif = { version = "0.1.6", default-features = false }
